### ISSUE TITLE
Poizvedba v tekma(x) ne dela

### ISSUE THREAD

**Issue by petrapodlogar** [Tejchy85/Skoki#2]
Funkcija tekma(x) v main.py najde tekme v sezoni x, ki so po datumu med '(x-1)-11-dd' in 'x-03-dd', ampak ne dela.

**Comment by jaanos** [comment]
Najprej poskrbite, da ima stolpec `datum` tip `DATE`. Če želite potem delati z datumi, jih lahko v Pythonu naredite z `datetime.date` (uvoziti bo torej potrebno `datetime`) in jih potem podati kot parametre k `execute`:
```python
cur.execute("SELECT * FROM tekma WHERE datum BETWEEN %s AND %s",
            [datetime.date(int(x)-1, 11, 1), datetime.date(int(x), 3, 31)])
```
Kot sem povedal na vajah, podatkov ne vstavljajte v SQL stavke s `format`, saj lahko to vodi do napadov [SQL](https://en.wikipedia.org/wiki/SQL_injection) [injection](https://xkcd.com/327/). Poleg tega znak `%` za ujemanje s poljubnim nizom deluje samo z operatorjema `LIKE` in `ILIKE` (slednji ni občutljiv na velikost črk), ne pa tudi z ostalimi operatorji.
