### ISSUE TITLE
Baza in spletni vmesnik

### ISSUE THREAD

**Issue by jaanos** [Tejchy85/Skoki#6]
Dodal bom povezavo na repozitorij predmeta, tako da se lahko z @alenFMF domenite za termin zagovora. Če boste do takrat še kaj spreminjali, mi javite, da posodobim povezavo.

Imam sicer še nekaj pripomb:
*  V tabeli `tekmovalec` je stolpec `rojstvo` tipa `text`, kar je sicer prikladno, da imate lahko v njem tako letnice kot celotne datume, a ni najlepša rešitev s stališča, da lahko vanj pišete tudi drugačne podatke. Svetujem, da mu tip spremenite v `date` - kjer imate samo letnice, naj bo datum kar 1. januar; lahko pa dodaste še en stolpec, ki bo povedal, ali naj se prikaže celoten datum ali samo letnica.
* V tabeli `uporabnik` imate stolpec `najljubsi_tekmovalci`, kjer imate naštete ID-je tekmovalcev kar v nizu. Namesto tega raje naredite vezno tabelo, ki bo povezovala uporabnike s tekmovalci. Glavni ključ uporabnika naj bo raje ID tipa `serial` (`username` je lahko `UNIQUE`).
* Izbirnik za urejanje po podanem stolpcu se pri meni prikaže zelo ozek, tako da ni takoj jasno, čemu je namenjen.
* Pri razvrščanju lahko pride do napadov [SQL](https://en.wikipedia.org/wiki/SQL_injection) [injection](https://xkcd.com/327/), saj v poizvedbo vstavljate niz, ki ga je poslal uporabnik (zlobni uporabnik bi lahko poslal tudi kaj, česar mu niste ponudili). V izogib takim napadom svetujem, da se namesto celotnega niza iz izbirnika pošlje samo zaporedna številka vnosa v seznamu - ko želi uporabnik urejati, se ta številka uporabi za pridobitev ustreznega niza iz že vnaprej pripravljenega seznama (tako si zagotovite, da poizvedba ne bo vsebovala nepreverjene vsebine).
* Funkcija *Postani admin* deluje le iz prve strani (manjka atribut `action` pri obrazcu). Morda bi bilo smiselno polje za admin geslo obravnavati kot polje za geslo (tudi pri registraciji)
* Namesto, da pišete *Če je pred vami prazna tabela ...*, bi lahko preverili, ali bi bila tabela res prazna, in v tem primeru izpisali ustrezno besedilo.
* V primerih, kjer lahko administrator izbira državo, bi bilo dobro prikazane kratice urediti (lahko pa bi prikazovali tudi imena držav).

**Comment by petrapodlogar** [comment]
Kako točno naj bi vezna tabela za najljubše tekmovalce izgledala?

**Comment by jaanos** [comment]
Dva stolpca, en referenca na uporabnika, drugi na ID tekmovalca, oba skupaj sta glavni ključ.

**Comment by Tejchy85** [comment]
Upoštevali in popravili sva vse alineje. Pri alineji, kjer je govora o najljubših tekmovalcih, sva edino obdržali glavni ključ username in ne ID, kot predlagano. Za to sva se odločili, ker vedno potrebujeva uporabniško ime in nama je z njim veliko lažje delati. Ker lahko obstaja samo eno uporabniško ime (če se uporabnik želi registrirati z že obstoječim uporabniškim imenom, mu sporočimo, da je to uporabniško ime že zasedeno) in je z njim enolično določena vrstica, meniva, da bi to lahko ostal glavni ključ.

**Comment by jaanos** [comment]
V redu, bom posodobil povezavo. Opažam sicer, da še vedno lahko pride do napadov SQL injection. Svetujem, da kar izven funkcij (tako da boste lahko uporabili isti seznam v več funkcijah) definirate seznam prikazanih nizov skupaj z nizom za vstavljanje v SQL stavek:
```python
moznosti_tekmovalci = [('FIS code - padajoče', 'fis_code DESC'),
                       ('FIS code - naraščajoče', 'fis_code ASC'),
                       ('Status - od A do Ž', 'status ASC'),
                       ('Status - od Ž do A', 'status DESC'),
                       ('Ime - od A do Ž', 'ime ASC'),
                       ('Ime - od Ž do A', 'ime DESC'),
                       ...]
```
`razvrscanje` bo sedaj indeks v tem seznamu - pri metodi `GET` podaste indeks privzete možnosti:
```python
return template('tekmovalci.html', tekmovalci=tekmovalci, razvrscanje=7, moznosti=moznosti_tekmovalci, sezone=sezone(), napakaO=None, napaka=None, username=username, admin=admin)
```
V predlogi potem prikažete niz, poslana vrednost pa naj bo enaka indeksu v seznamu:
```HTML
            <select type="text" name="razvrscanje" value="" class="form-control" required="true">
                %for i, (raz, sql) in enumerate(moznosti):
                    <option value="{{i}}"
                    %if i == razvrscanje:
                    selected
                    %end
                    >{{raz}}</option>
                %end
            </select>
```
Pri metodi `POST` potem preberete poslani indeks in ustrezen niz dobite iz seznama:
```python
raz = int(request.forms.razvrscanje)
...
cur.execute("SELECT * FROM tekmovalec ORDER BY " + 
            moznosti_tekmovalci[raz][1])
```
Če bo uporabnik poslal neveljavno vrednost, bo potem prišlo do napake - bodisi pri pretvorbi v celo število, bodisi pri indeksiranju seznama.

**Comment by Tejchy85** [comment]
Popravila sem razvrščanja kot ste predlagali. Upam da sem pravilno razumela in sedaj ne more priti več do  napadov SQL injection.

**Comment by jaanos** [comment]
Se opravičujem za pozen odgovor. Sedaj izgleda v redu, tako da bom posodobil povezavo.
